# Generate binary releases when a tag is pushed
name: release

on:
  push:
    tags:
      - '*.*.*' #Run when tag matches *.*.*, i.e. 0.0.1

jobs:
  build:
    name: Build release artifacts for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
            linux,
            windows,
            macos
        ]
        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: "target/dist/*.zip"
            asset_name: mdbook-i18n-helpers-linux
          - name: windows
            os: windows-latest
            artifact_name: "target/dist/*.zip"
            asset_name: mdbook-i18n-helpers-windows
          - name: macos
            os: macos-latest
            artifact_name: "target/dist/*.zip"
            asset_name: mdbook-i18n-helpers-macos
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - name: Build
      run: cargo xtask dist
    - name: Upload binaries to release
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.artifact_name }}

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch Pre-Compiled Binaries
        uses: actions/download-artifact@v2
        with:
          path: public

      - name: Publish the Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "public/mdbook-i18n-helpers-*/*.zip"
          body: |
            Released ${{ github.ref }}.
          token: ${{ secrets.GITHUB_TOKEN }}
